### ISSUE TITLE
Error finding dawn binaries on MacOS 

### ISSUE THREAD

**Issue by Nazariglez** [zig-gamedev/zig-gamedev#434] opened 2023-10-29 18:44 UTC
Hello!

I am having some issues trying to setup a project with `zgpu`. It seems that the linking is going wrong and I am not sure why, I tried with your examples and they work, I also cloned https://github.com/ckrowland/simulations/tree/main and it also works...

This is my project zon: https://github.com/Nazariglez/zgk/blob/f/exp2/build.zig.zon
And my build.zig: https://github.com/Nazariglez/zgk/blob/f/exp2/build.zig

This is the error I got trying to run gfx_triangle-run:
```
➜  zgk git:(f/exp2) zig-dev build gfx_triangle-run 
zig build-exe gfx_triangle Debug native: error: error: unable to find Dynamic system library 'dawn' using strategy 'paths_first'. searched paths:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/lib/libdawn.tbd
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/lib/libdawn.dylib
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/lib/libdawn.so
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/lib/libdawn.a

zig build-exe gfx_triangle Debug native: error: the following command exited with error code 1:
/Users/nazariglez/Downloads/zig-dev/zig build-exe /Users/nazariglez/personal/zgk/examples/gfx_triangle/src/main.zig /Users/nazariglez/personal/zgk/zig-cache/o/28e519e5da7ece032f517e0ef182a250/libzgk.a /Users/nazariglez/personal/zgk/zig-cache/o/3800de1404671291f1d6e7c93ce8fae1/liblibglfw.a -lobjc -ldawn -lc++ -lc -fno-strip --cache-dir /Users/nazariglez/personal/zgk/zig-cache --global-cache-dir /Users/nazariglez/.cache/zig --name gfx_triangle --mod zgpu:zgpu_options,zglfw,zpool:/Users/nazariglez/personal/zgk/deps/zig-gamedev/libs/zgpu/src/zgpu.zig --mod zgk:zglfw,zpool,zgpu:/Users/nazariglez/personal/zgk/src/main.zig --mod zpool::/Users/nazariglez/personal/zgk/deps/zig-gamedev/libs/zpool/src/main.zig --mod zglfw::/Users/nazariglez/personal/zgk/deps/zig-gamedev/libs/zglfw/src/zglfw.zig --mod zgpu_options::/Users/nazariglez/personal/zgk/zig-cache/c/16e69f770bed816ccd730af23169a19d/options.zig --deps zgk -framework QuartzCore -framework CoreFoundation -framework Metal -framework AppKit -framework CoreServices -framework CoreGraphics -framework IOSurface -framework Foundation -framework IOKit -fno-lto --listen=- 
Build Summary: 3/8 steps succeeded; 1 failed (disable with --summary none)
gfx_triangle-run transitive failure
└─ run gfx_triangle transitive failure
   ├─ zig build-exe gfx_triangle Debug native failure
   └─ gfx_triangle transitive failure
      └─ install gfx_triangle transitive failure
         └─ zig build-exe gfx_triangle Debug native (+2 more reused dependencies)
error: the following build command failed with exit code 1:
/Users/nazariglez/personal/zgk/zig-cache/o/332336690040ac3fe9dccbaef241a8ac/build /Users/nazariglez/Downloads/zig-dev/zig /Users/nazariglez/personal/zgk /Users/nazariglez/personal/zgk/zig-cache /Users/nazariglez/.cache/zig --seed 0x36adec30 gfx_triangle-run
```

I am learning zig right now, and I am not sure how this `zon` package linking should work, where are the binaries downloaded, or if I did something plain wrong. Any help or advice with this will be great. Thanks!

Edit: Zig `0.12.0-dev.1286+cc394431a`

**Comment by hazeycode** [comment] 2023-11-12 13:07
Hey! Did you copy the system-sdk folder next to zgpu folder in your project?

zgpu is not currently compatible with the package manger.

**Comment by hazeycode** [comment] 2024-01-08 20:02
Hey I downloaded your project and it works for me using Zig 0.12.0-dev.1871+e426ae43a on MacOS 13.5. I think there may have been a linker regression on the version of Zig you were using. Can you try again using this version of Zig?

**Comment by Nazariglez** [comment] 2024-01-11 21:34
Still the same issue. Although I think this is not a big deal, I realized that I can manually copy the libraries asked to the directory and it just works. My guess is that the package manager should do this?

We can close the issue if you want, it seems to be something on my end or something easy to "fix" manually. Thanks!!

**Comment by hazeycode** [comment] 2024-01-11 21:53
The package manager should be pulling the dawn libs to a local directory and then link them. It looks like something is going wrong there and so it is then looking for the libs in the standard system locations.

I guess there there could be something different with our environments.

It would be good to get to the bottom of this so others don't hit the same thing. Could you run `zig env` and post the output? Here is mine:

```
{
 "zig_exe": "/Users/chris/zig/0.12.0-dev.1871+e426ae43a/files/zig",
 "lib_dir": "/Users/chris/zig/0.12.0-dev.1871+e426ae43a/files/lib",
 "std_dir": "/Users/chris/zig/0.12.0-dev.1871+e426ae43a/files/lib/std",
 "global_cache_dir": "/Users/chris/.cache/zig",
 "version": "0.12.0-dev.1871+e426ae43a",
 "target": "x86_64-macos.13.5...13.5-none",
 "env": {
  "ZIG_GLOBAL_CACHE_DIR": null,
  "ZIG_LOCAL_CACHE_DIR": null,
  "ZIG_LIB_DIR": null,
  "ZIG_LIBC": null,
  "ZIG_BUILD_RUNNER": null,
  "ZIG_VERBOSE_LINK": null,
  "ZIG_VERBOSE_CC": null,
  "ZIG_BTRFS_WORKAROUND": null,
  "CC": null,
  "NO_COLOR": null,
  "XDG_CACHE_HOME": null,
  "HOME": "/Users/chris"
 }
}
```

Or If you prefer to just go with the workaround, that's ok, feel free to close the issue.

**Comment by Nazariglez** [comment] 2024-01-12 20:27
Sure thing, let's find out what's going on:
```
➜  ~ zig-dev env
{
 "zig_exe": "/Users/nazariglez/Downloads/zig-dev/zig",
 "lib_dir": "Downloads/zig-dev/lib",
 "std_dir": "Downloads/zig-dev/lib/std",
 "global_cache_dir": "/Users/nazariglez/.cache/zig",
 "version": "0.12.0-dev.1871+e426ae43a",
 "target": "x86_64-macos.14.2.1...14.2.1-none",
 "env": {
  "ZIG_GLOBAL_CACHE_DIR": null,
  "ZIG_LOCAL_CACHE_DIR": null,
  "ZIG_LIB_DIR": null,
  "ZIG_LIBC": null,
  "ZIG_BUILD_RUNNER": null,
  "ZIG_VERBOSE_LINK": null,
  "ZIG_VERBOSE_CC": null,
  "ZIG_BTRFS_WORKAROUND": null,
  "CC": null,
  "NO_COLOR": null,
  "XDG_CACHE_HOME": null,
  "HOME": "/Users/nazariglez"
 }
}
````
My MacOS version was 13.3, I updated the OS and still have the issue, just FYI, to discard that this is because of Sonoma. 

The main difference I see is that all your routes are absolute while mines are mixed with `relatives`.

**Comment by hazeycode** [comment] 2024-01-13 12:20
Thanks!

The dawn lib should of been downloaded to `~/.cache/zig/p/1220b1f02f2f7edd98a078c64e3100907d90311d94880a3cc5927e1ac009d002667a/libdawn.a`, does this exist for you?

If it doesn't you can try running `zig fetch 1220b1f02f2f7edd98a078c64e3100907d90311d94880a3cc5927e1ac009d002667a`

**Comment by Nazariglez** [comment] 2024-01-13 18:57
The lib is definitively there: 
```
➜  ~ ls -la ~/.cache/zig/p/1220b1f02f2f7edd98a078c64e3100907d90311d94880a3cc5927e1ac009d002667a/
total 73880
drwxr-xr-x   6 nazariglez  staff       192 Oct 26 19:45 .
drwxr-xr-x  36 nazariglez  staff      1152 Oct 26 19:45 ..
-rw-r--r--   1 nazariglez  staff        17 Oct 26 19:45 .gitattributes
-rw-r--r--   1 nazariglez  staff        26 Oct 26 19:45 README.md
-rw-r--r--   1 nazariglez  staff        65 Oct 26 19:45 build.zig
-rw-r--r--   1 nazariglez  staff  37811488 Oct 26 19:45 libdawn.a

```

**Comment by hazeycode** [comment] 2024-03-20 02:34
Maybe this is fixed by https://github.com/zig-gamedev/zig-gamedev/pull/518. Can you confirm you are still having this issue @Nazariglez?

**Comment by hazeycode** [comment] 2024-04-13 15:49
Feel free to reopen if this this isn't working for you still

**Closed by hazeycode** 2024-04-13 15:49 UTC

**Comment by nilu2039** [comment] 2025-03-15 14:51
hey any update on this error?
