### ISSUE TITLE
physically_based_rendering_wgpu-run demo not working on macos

### ISSUE THREAD

**Issue by giusdp** [zig-gamedev/zig-gamedev#632] opened 2024-07-06 08:34 UTC
Hi folks!

I'm new to zig and zig-gamedev. I was exploring the project and following the readme first thing I did was running the demo with `zib build physically_based_rendering_wgpu-run`.

With the first launch the screen was showing me the small Imgui (I think it is) menu on top of a black screen. 
I resized the window and everything turned into a magenta color, the menu disappeared as well.

I closed the window and tried to run again and this time it was just all magenta. 
At the third try the screen was flickering showing me the 3D scene one frame and everything magenta the next frame continuously til the laptop froze.

I'm on a M2 macbook pro. My zig version is 0.13.0-dev.351+64ef45eb0

**Comment by hazeycode** [comment] 2024-07-06 14:58
Hi

I'm sorry to say that we have issues with zgpu/Dawn on macOS.

Duplicate of #411

**Closed by hazeycode** 2024-07-06 14:58 UTC
